### ISSUE TITLE
Change the output format for analyze_sentiment

### ISSUE THREAD

**Issue by shobrook** [shobrook/TypeSense#24]
From `{"hash": {"sentiment" : int(), "author" : bool()}, ...}` to `[{"hash": str(), "sentiment": int(), "author": bool()}, ...]`.

**Comment by alichtman** [comment]
https://giphy.com/gifs/sara-bareilles-fs5OIyvjzw61q

**Comment by alichtman** [comment]
jk I'll do this eventually
