### ISSUE TITLE
Facebook Login

### ISSUE THREAD

**Issue by alichtman** [shobrook/TypeSense#52]
No point in designing a secure registration system only to switch to FB auth later. 

+ https://stackoverflow.com/a/12538742/8740440
+ https://github.com/blackgirl/Facebook_Oauth2_sample_for_extensions
+ https://medium.com/@evangow/truly-serverless-build-an-mvp-using-the-facebook-groups-api-deploy-as-a-browser-extension-1c66d4fa256f

^^ This looks promising, maybe. @shobrook, read step 3 and lmk if this is applicable. I understand Step 1, but I don't know where the rest of the code goes.

+ ~https://developer.chrome.com/apps/app_identity~

~This is used to get Oauth2 keys. Need to add "identity" permission in `manifest.json`~

~We could do Google Auth pretty easily, but it makes a ton more sense to do FB auth. It's a pain, but...~

**Comment by alichtman** [comment]
Here's how to do it: https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow

**Comment by alichtman** [comment]
Possibly use this? https://github.com/python-social-auth/social-app-flask

**Comment by alichtman** [comment]
Add `public_profile` permission and pull FB id from `id` property of it.

**Comment by shobrook** [comment]
So, we need to add a "Login with Facebook" button to `popup.html` that's displayed when a user first installs the app. That button should link to [this](https://www.facebook.com/dialog/oauth?client_id=1905953259716133&response_type=token&redirect_uri=https://www.facebook.com/connect/login_success.html). Then, we need to write a function in `background.js` to handle the redirect URI (which should return success and an access token). That function should store the access token in localStorage, refresh Messenger, and load the graph in `popup.html`.

**Comment by alichtman** [comment]
+ https://developers.facebook.com/docs/facebook-login/web
+ https://developers.facebook.com/docs/facebook-login
+ https://developers.facebook.com/docs/facebook-login/web/login-button

**Comment by alichtman** [comment]
https://github.com/ALiangLiang/Counter-for-Messenger

**Comment by alichtman** [comment]
I've never been so happy to tag something `wontfix` before.
